### ISSUE TITLE
ImportError: cannot import name 'Monitor' from 'gym.wrappers'

### ISSUE THREAD

**Issue by lu0909** [Optical-Networks-Group/rsa-rl-tutorials#1]
The error message is as follows:
Traceback (most recent call last):
File "F:\xx\rsa-rl\code\rsa-rl-tutorials-master\rsa-rl-tutorials-master\examples\ksp-agent.py", line 8, in
from rsarl.envs import DeepRMSAEnv
File "", line 259, in load_module
File "C:\Users\xx.conda\envs\pytorch2\lib\site-packages\rsarl-1.0.0-py3.9.egg\rsarl_init_.py", line 2, in
File "", line 259, in load_module
File "C:\Users\xx.conda\envs\pytorch2\lib\site-packages\rsarl-1.0.0-py3.9.egg\rsarl\utils_init_.py", line 3, in
File "", line 259, in load_module
File "C:\Users\xx.conda\envs\pytorch2\lib\site-packages\rsarl-1.0.0-py3.9.egg\rsarl\utils\random_seed.py", line 2, in
File "", line 259, in load_module
File "C:\Users\xx.conda\envs\pytorch2\lib\site-packages\pfrl-0.3.0-py3.9.egg\pfrl_init_.py", line 20, in
File "", line 259, in load_module
File "C:\Users\xx.conda\envs\pytorch2\lib\site-packages\pfrl-0.3.0-py3.9.egg\pfrl\wrappers_init_.py", line 4, in
File "", line 259, in load_module
File "C:\Users\xx.conda\envs\pytorch2\lib\site-packages\pfrl-0.3.0-py3.9.egg\pfrl\wrappers\monitor.py", line 4, in
ImportError: cannot import name 'Monitor' from 'gym.wrappers' (C:\Users\xx.conda\envs\pytorch2\lib\site-packages\gym-0.23.1-py3.9.egg\gym\wrappers_init_.py)

System Info
Describe the characteristic of your environment:
OS/version is windows10.
Python version is python3.9.

**Comment by lu0909** [comment]
'Monitor' has been removed from 'gym.wrappers' in gym0.23. 
runing in the gym0.21, it is successful.
